# Generated by Django 3.2.6 on 2021-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.TextField(default='', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='pattern',
            old_name='boss_name',
            new_name='boss',
        ),
    ]
