# Generated by Django 3.2.6 on 2021-08-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0003_auto_20210816_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='guide',
            field=models.TextField(default='공략없음', max_length=1000, null=True),
        ),
    ]
