# Generated by Django 3.2.6 on 2021-08-16 17:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0006_alter_pattern_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='guide',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
